name: Dependency Cache Test

on:
  push:
    branches:
      - main

jobs:
  cache-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
          key: cache-24445d8

      - name: prime-cache-24445d8
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
